//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAuthenticateWCF")]
    public interface IAuthenticateWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticateWCF/Login", ReplyAction="http://tempuri.org/IAuthenticateWCF/LoginResponse")]
        bool Login(string un, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticateWCF/Login", ReplyAction="http://tempuri.org/IAuthenticateWCF/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string un, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticateWCF/Register", ReplyAction="http://tempuri.org/IAuthenticateWCF/RegisterResponse")]
        bool Register(string un, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthenticateWCF/Register", ReplyAction="http://tempuri.org/IAuthenticateWCF/RegisterResponse")]
        System.Threading.Tasks.Task<bool> RegisterAsync(string un, string pw);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthenticateWCFChannel : Service.ServiceReference1.IAuthenticateWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticateWCFClient : System.ServiceModel.ClientBase<Service.ServiceReference1.IAuthenticateWCF>, Service.ServiceReference1.IAuthenticateWCF {
        
        public AuthenticateWCFClient() {
        }
        
        public AuthenticateWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticateWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticateWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticateWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string un, string pw) {
            return base.Channel.Login(un, pw);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string un, string pw) {
            return base.Channel.LoginAsync(un, pw);
        }
        
        public bool Register(string un, string pw) {
            return base.Channel.Register(un, pw);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterAsync(string un, string pw) {
            return base.Channel.RegisterAsync(un, pw);
        }
    }
}
