//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthenticaitonWCFConsole.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/MusclesAuthenticationWCF")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ILoginWCF")]
    public interface ILoginWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginWCF/GetData", ReplyAction="http://tempuri.org/ILoginWCF/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginWCF/GetData", ReplyAction="http://tempuri.org/ILoginWCF/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginWCF/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ILoginWCF/GetDataUsingDataContractResponse")]
        AuthenticaitonWCFConsole.ServiceReference1.CompositeType GetDataUsingDataContract(AuthenticaitonWCFConsole.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginWCF/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ILoginWCF/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<AuthenticaitonWCFConsole.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(AuthenticaitonWCFConsole.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginWCF/Login", ReplyAction="http://tempuri.org/ILoginWCF/LoginResponse")]
        bool Login(string un, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginWCF/Login", ReplyAction="http://tempuri.org/ILoginWCF/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string un, string pw);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginWCFChannel : AuthenticaitonWCFConsole.ServiceReference1.ILoginWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginWCFImplClient : System.ServiceModel.ClientBase<AuthenticaitonWCFConsole.ServiceReference1.ILoginWCF>, AuthenticaitonWCFConsole.ServiceReference1.ILoginWCF {
        
        public LoginWCFImplClient() {
        }
        
        public LoginWCFImplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginWCFImplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginWCFImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginWCFImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public AuthenticaitonWCFConsole.ServiceReference1.CompositeType GetDataUsingDataContract(AuthenticaitonWCFConsole.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<AuthenticaitonWCFConsole.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(AuthenticaitonWCFConsole.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public bool Login(string un, string pw) {
            return base.Channel.Login(un, pw);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string un, string pw) {
            return base.Channel.LoginAsync(un, pw);
        }
    }
}
